#
#   PROGRAM:    CSCI 241 Assignment 7 - makefile
#   PROGRAMMER: Kevin Kang
#   LOGON ID:   z1837081
#   SECTION:    4
#   TA: Abdul   Subhan Moin Syed
#   DUE DATE:   Thursday, 11/16/2017 by 11:59 pm 
#
#   FUNCTION:   makefile for assignment 7
#

assign: assign7.o
	g++ -Wall -std=c++11 -o assign7 assign7.o

assign7.o: assign7.cpp Stack.h
	g++ -Wall -std=c++11 -c assign7.cpp

clean:
	rm *.o assign7


               
