#
#   PROGRAM:    CSCI 241 Assignment 8 - makefile
#   PROGRAMMER: Kevin Kang
#   LOGON ID:   z1837081
#   SECTION:    4
#   TA: Abdul   Subhan Moin Syed
#   DUE DATE:   Wednesday, 11/29/2017 by 11:59 pm 
#
#   FUNCTION:   makefile for assignment 8
#

assign: assign8.o
	g++ -Wall -std=c++11 -o assign8 assign8.o

assign8.o: assign8.cpp sorts.h
	g++ -Wall -std=c++11 -c assign8.cpp

clean:
	rm *.o assign8


               
