#
#   PROGRAM:    CSCI 241 Assignment 6 - makefile
#   PROGRAMMER: Kevin Kang
#   LOGON ID:   z1837081
#   SECTION:    4
#   TA: Abdul   Subhan Moin Syed
#   DUE DATE:   Thursday, 11/9/2017 by 11:59 pm 
#
#   FUNCTION:   makefile for assignment 6
#

assign: assign6.o
	g++ -Wall -std=c++11 -o assign6 assign6.o

assign6.o: assign6.cpp Queue.h
	g++ -Wall -std=c++11 -c assign6.cpp

clean:
	rm *.o assign6


               
